package formulario;

import java.awt.CardLayout;
import java.awt.Color;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JUAN100CORR
 */
public final class menuprincipal extends javax.swing.JFrame {

    pnl_alta pnl_alta_empleado;
    
/**
     * Creates new form menuprincipal
     */
        CardLayout vista;
    
     pnl_busqueda pnl_busqueda_empleado = new pnl_busqueda();
    
    CardLayout vista2;
    
      pnl_modificacion pnl_modificar_empleado = new pnl_modificacion();
    
    CardLayout vista3;
    
    
    public menuprincipal() throws SQLException {
        this.pnl_alta_empleado = new pnl_alta();
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        iconoFormulario();
        vista = (CardLayout) vistaprincipal.getLayout();
        vista2 = (CardLayout) vistaprincipal.getLayout();
        vista3 = (CardLayout) vistaprincipal.getLayout();
          BTN_ELIMINAR.setEnabled(false);
           BTN_MODIFICAR.setEnabled(false);
    }
    
    

    public void iconoFormulario() {

        URL url = getClass().getResource("/imagenes/salud.png");
        ImageIcon icono = new ImageIcon(url);
        setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTN_MODIFICAR = new javax.swing.JToggleButton();
        BTN_AGREGAR = new javax.swing.JToggleButton();
        BTN_ELIMINAR = new javax.swing.JToggleButton();
        BTN_BUSCAR = new javax.swing.JToggleButton();
        BTN_CERRAR = new javax.swing.JButton();
        vistaprincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CENTRO DE SALUD");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 46));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU DEL SISTEMA");

        BTN_MODIFICAR.setBackground(new java.awt.Color(239, 239, 239));
        BTN_MODIFICAR.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        BTN_MODIFICAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        BTN_MODIFICAR.setSelected(true);
        BTN_MODIFICAR.setText("MODIFICAR PACIENTE");
        BTN_MODIFICAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_MODIFICAR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BTN_MODIFICAR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        BTN_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MODIFICARActionPerformed(evt);
            }
        });

        BTN_AGREGAR.setBackground(new java.awt.Color(239, 239, 239));
        BTN_AGREGAR.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        BTN_AGREGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        BTN_AGREGAR.setSelected(true);
        BTN_AGREGAR.setText("REGISTRO DE NUEVO PACIENTE");
        BTN_AGREGAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_AGREGAR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BTN_AGREGAR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        BTN_AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AGREGARActionPerformed(evt);
            }
        });

        BTN_ELIMINAR.setBackground(new java.awt.Color(239, 239, 239));
        BTN_ELIMINAR.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        BTN_ELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BTN_ELIMINAR.setSelected(true);
        BTN_ELIMINAR.setText("ELIMINAR PACIENTE");
        BTN_ELIMINAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_ELIMINAR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BTN_ELIMINAR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });

        BTN_BUSCAR.setBackground(new java.awt.Color(239, 239, 239));
        BTN_BUSCAR.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        BTN_BUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BUSCAR.png"))); // NOI18N
        BTN_BUSCAR.setSelected(true);
        BTN_BUSCAR.setText("BUSCAR PACIENTE");
        BTN_BUSCAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_BUSCAR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BTN_BUSCAR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        BTN_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCARActionPerformed(evt);
            }
        });

        BTN_CERRAR.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        BTN_CERRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close_Icon_Circle_icon-icons.com_69142.png"))); // NOI18N
        BTN_CERRAR.setText("CERRAR");
        BTN_CERRAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_CERRAR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BTN_CERRAR.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        BTN_CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CERRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTN_BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTN_ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTN_MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTN_AGREGAR)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(BTN_CERRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BTN_AGREGAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_MODIFICAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_ELIMINAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_BUSCAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(BTN_CERRAR)
                .addGap(33, 33, 33))
        );

        vistaprincipal.setBackground(new java.awt.Color(102, 0, 46));
        vistaprincipal.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gobmx.png"))); // NOI18N
        vistaprincipal.add(jLabel2, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1229, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vistaprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CERRARActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_CERRARActionPerformed

    private void BTN_AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AGREGARActionPerformed
     
     vistaprincipal.add(pnl_alta_empleado,"alta");
     vista.show(vistaprincipal,"alta");
     SwingUtilities.updateComponentTreeUI(this);
     this.repaint();
     BTN_AGREGAR.setBackground(Color.WHITE);  

        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_AGREGARActionPerformed

    private void BTN_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MODIFICARActionPerformed
   
     vistaprincipal.add(pnl_modificar_empleado,"busqueda");
     vista3.show(vistaprincipal,"busqueda");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        BTN_AGREGAR.setBackground(Color.WHITE); 
       
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_MODIFICARActionPerformed

    private void BTN_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCARActionPerformed
     vistaprincipal.add(pnl_busqueda_empleado,"busqueda");
     vista2.show(vistaprincipal,"busqueda");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        BTN_AGREGAR.setBackground(Color.WHITE); 
        
        pnl_busqueda_empleado.tabla.fireTableDataChanged();
        /*
        EN CASO DE FALLA HABILITALA PAPITO CHULO
        */
        pnl_busqueda_empleado.ins_curp.setText("");
        pnl_busqueda_empleado.limpiar();
        pnl_busqueda_empleado.cargardatostabla();
        
    
      
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_BUSCARActionPerformed

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed

           
// TODO add your handling code here:
    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menuprincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTN_AGREGAR;
    private javax.swing.JToggleButton BTN_BUSCAR;
    private javax.swing.JButton BTN_CERRAR;
    private javax.swing.JToggleButton BTN_ELIMINAR;
    private javax.swing.JToggleButton BTN_MODIFICAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel vistaprincipal;
    // End of variables declaration//GEN-END:variables

    private void setExtendedSatate(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setIconImage(ImageIcon icono) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
