/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

/**
 *
 * @author JUAN100CORR
 */
public final class pnl_modificacion extends javax.swing.JPanel {

    /**
     * Creates new form pnl_alta
     */
    public pnl_modificacion() {
        initComponents();
        rellenar_comboaño();
        rellenar_combomes();
        rellenar_combodia();
        rellenar_combohijos();
    
    }
    
    public void rellenar_comboaño(){
     for(int i = 1930; i <= 2020; i++){
         ins_año.addItem(String.valueOf(i));
    }
    }
     public void rellenar_combomes(){
     for(int i = 1; i <= 12; i++){
         ins_mes.addItem(String.valueOf(i));
    }
     }
     
     public void rellenar_combodia(){
     for(int i = 1; i <= 31; i++){
         ins_dia.addItem(String.valueOf(i));
    }
    }
     public void rellenar_combohijos(){
     for(int i = 1; i <= 20; i++){
         ins_numhijos.addItem(String.valueOf(i));
    }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JLabel();
        txt_edad = new javax.swing.JLabel();
        txt_sexo = new javax.swing.JLabel();
        txt_nacimiento = new javax.swing.JLabel();
        txt_hijos = new javax.swing.JLabel();
        txt_civil = new javax.swing.JLabel();
        txt_hrstrabajo = new javax.swing.JLabel();
        txt_escolaridad = new javax.swing.JLabel();
        txt_profesion = new javax.swing.JLabel();
        txt_ocupacion = new javax.swing.JLabel();
        txt_nocasa = new javax.swing.JLabel();
        txt_religion = new javax.swing.JLabel();
        txt_telefonomovil = new javax.swing.JLabel();
        txt_correo = new javax.swing.JLabel();
        ins_nombre = new javax.swing.JTextField();
        ins_edad = new javax.swing.JTextField();
        ins_sexo = new javax.swing.JComboBox<>();
        ins_estadocivil = new javax.swing.JComboBox<>();
        ins_año = new javax.swing.JComboBox<>();
        ins_mes = new javax.swing.JComboBox<>();
        ins_dia = new javax.swing.JComboBox<>();
        ins_religion = new javax.swing.JTextField();
        ins_telefonomovil = new javax.swing.JTextField();
        ins_escolaridad1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ins_horastra = new javax.swing.JTextField();
        ins_profesion = new javax.swing.JTextField();
        ins_ocupacion = new javax.swing.JTextField();
        ins_telcasa = new javax.swing.JTextField();
        ins_correo = new javax.swing.JTextField();
        ins_numhijos = new javax.swing.JComboBox<>();
        OPCIONES = new javax.swing.JPanel();
        bot_agregar = new javax.swing.JButton();
        bot_agregar1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("MODIFICAR PACIENTE");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "INGRESE LOS DATOS DEL PACIENTE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        txt_nombre.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_nombre.setText("NOMBRE");

        txt_edad.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_edad.setText("EDAD");

        txt_sexo.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_sexo.setText("SEXO");

        txt_nacimiento.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_nacimiento.setText("AÑO DE NACIMIENTO");

        txt_hijos.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_hijos.setText("NUMERO DE HIJOS");

        txt_civil.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_civil.setText("ESTADO CIVIL");

        txt_hrstrabajo.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_hrstrabajo.setText("HRS. DE TRABAJO");

        txt_escolaridad.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_escolaridad.setText("ESCOLARIDAD");

        txt_profesion.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_profesion.setText("PROFESION");

        txt_ocupacion.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_ocupacion.setText("OCUPACION");

        txt_nocasa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_nocasa.setText("TELEFONO DE CASA");

        txt_religion.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_religion.setText("RELIGION");

        txt_telefonomovil.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_telefonomovil.setText("TELEFONO MOVIL");

        txt_correo.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_correo.setText("CORREO ELECTRONICO");

        ins_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "FEMENINO", "MASCULINO", "OTRO" }));

        ins_estadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "SOLTERO", "CASADO", "OTRO" }));

        ins_año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AÑO" }));
        ins_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_añoActionPerformed(evt);
            }
        });

        ins_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MES" }));
        ins_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_mesActionPerformed(evt);
            }
        });

        ins_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIA" }));

        ins_escolaridad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "PRIMARIA", "SECUNDARIA", "PREPARATORIA", "BACHILLERARO", "LICENCIATURA", "POSGRADO" }));

        ins_numhijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_edad)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_telefonomovil)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_civil)
                                        .addComponent(txt_nacimiento)
                                        .addComponent(txt_sexo)
                                        .addComponent(txt_nombre))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ins_telefonomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(ins_año, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ins_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ins_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ins_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ins_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ins_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ins_numhijos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ins_estadocivil, javax.swing.GroupLayout.Alignment.LEADING, 0, 179, Short.MAX_VALUE)))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_ocupacion)
                                        .addComponent(txt_nocasa)
                                        .addComponent(txt_religion)
                                        .addComponent(txt_profesion)
                                        .addComponent(txt_hrstrabajo)
                                        .addComponent(txt_escolaridad)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(txt_correo))))
                        .addComponent(txt_hijos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ins_escolaridad1, 0, 179, Short.MAX_VALUE)
                    .addComponent(ins_religion)
                    .addComponent(ins_horastra)
                    .addComponent(ins_profesion)
                    .addComponent(ins_ocupacion)
                    .addComponent(ins_telcasa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ins_correo))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hrstrabajo)
                            .addComponent(ins_horastra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ins_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre)
                            .addComponent(txt_escolaridad)
                            .addComponent(ins_escolaridad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_edad)
                            .addComponent(ins_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sexo)
                            .addComponent(ins_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_profesion)
                            .addComponent(ins_profesion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nacimiento)
                    .addComponent(ins_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_religion)
                    .addComponent(ins_religion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hijos)
                    .addComponent(txt_ocupacion)
                    .addComponent(ins_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_numhijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_civil)
                    .addComponent(ins_estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nocasa)
                    .addComponent(ins_telcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_telefonomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefonomovil)
                    .addComponent(txt_correo)
                    .addComponent(ins_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );

        OPCIONES.setBackground(new java.awt.Color(255, 255, 255));
        OPCIONES.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPCIONES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        bot_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        bot_agregar.setText("AGREGAR");

        bot_agregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar (2).png"))); // NOI18N
        bot_agregar1.setText("BORRAR");

        javax.swing.GroupLayout OPCIONESLayout = new javax.swing.GroupLayout(OPCIONES);
        OPCIONES.setLayout(OPCIONESLayout);
        OPCIONESLayout.setHorizontalGroup(
            OPCIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OPCIONESLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(OPCIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bot_agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        OPCIONESLayout.setVerticalGroup(
            OPCIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OPCIONESLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(bot_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(bot_agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OPCIONES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(573, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OPCIONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ins_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_mesActionPerformed

    private void ins_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_añoActionPerformed
         
         // TODO add your handling code here:
    }//GEN-LAST:event_ins_añoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OPCIONES;
    private javax.swing.JButton bot_agregar;
    private javax.swing.JButton bot_agregar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> ins_año;
    private javax.swing.JTextField ins_correo;
    private javax.swing.JComboBox<String> ins_dia;
    private javax.swing.JTextField ins_edad;
    private javax.swing.JComboBox<String> ins_escolaridad1;
    private javax.swing.JComboBox<String> ins_estadocivil;
    private javax.swing.JTextField ins_horastra;
    private javax.swing.JComboBox<String> ins_mes;
    private javax.swing.JTextField ins_nombre;
    private javax.swing.JComboBox<String> ins_numhijos;
    private javax.swing.JTextField ins_ocupacion;
    private javax.swing.JTextField ins_profesion;
    private javax.swing.JTextField ins_religion;
    private javax.swing.JComboBox<String> ins_sexo;
    private javax.swing.JTextField ins_telcasa;
    private javax.swing.JTextField ins_telefonomovil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_civil;
    private javax.swing.JLabel txt_correo;
    private javax.swing.JLabel txt_edad;
    private javax.swing.JLabel txt_escolaridad;
    private javax.swing.JLabel txt_hijos;
    private javax.swing.JLabel txt_hrstrabajo;
    private javax.swing.JLabel txt_nacimiento;
    private javax.swing.JLabel txt_nocasa;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_ocupacion;
    private javax.swing.JLabel txt_profesion;
    private javax.swing.JLabel txt_religion;
    private javax.swing.JLabel txt_sexo;
    private javax.swing.JLabel txt_telefonomovil;
    // End of variables declaration//GEN-END:variables
}
