/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import DAO.CodigopostalDAO;
import DAO.ColoniaDAO;
import DAO.MunicipioDAO;
import VO.CodigopostalVO;
import VO.MunicipioVO;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import mysql.conexion;
import mysql.metodos;
import mysql.metodos2;

/**
 *
 * @author JUAN100CORR
 */
public final class pnl_alta extends javax.swing.JPanel {

    /**
     * Creates new form pnl_alta
     */
  MunicipioDAO MUN = new MunicipioDAO();
    CodigopostalDAO COP = new CodigopostalDAO();
    ColoniaDAO COL = new ColoniaDAO();
    
    
    metodos metodos = new metodos();
    
    
    String curp1; 
    String nombre1; 
    String apellidop1;
    String apellidom1;
    int edad1;
    String sexo1; 
    int año1;
    int nohijos1; 
    String estcivil1; 
    String escolaridad1;
    String hrtrabajo1; 
    String Ocupacion1; 
    String Religion1; 
    int tel_cas1; 
    String tel_mov1; 
    String correo1;
    
    metodos2 metodos2 = new metodos2();
    
    
    
    String calle1; 
    String numext1; 
    String clvmun;
    String cpnum; 
    String clvcol; 
    String idpa;
    
    
    public pnl_alta() throws SQLException {
        initComponents();
        rellenar_comboaño();
        rellenar_combohijos();
        MUN.listar_municipios(ins_municipio);
     
      
     
        
        bot_agregar.setEnabled(false);
        
    
    }
    
    public void rellenar_comboaño(){
     for(int i = 1930; i <= 2020; i++){
         ins_año.addItem(String.valueOf(i));
    }
    }

     public void rellenar_combohijos(){
     for(int i = 0; i <= 20; i++){
         ins_numhijos.addItem(String.valueOf(i));
    }
    }
     

    public void clean(){
    ins_nombre.setText("");
    ins_apellidop.setText("");
    ins_apellidom.setText("");
    ins_edad.setText("");
    ins_sexo.setSelectedIndex(0);
    ins_año.setSelectedIndex(0);
    ins_numhijos.setSelectedIndex(0);
    ins_estadocivil.setSelectedIndex(0);
    ins_telefonomovil.setText("");
    ins_escolaridad1.setSelectedIndex(0);
    ins_horastra.setSelectedIndex(0);
    ins_curp.setText("");
    ins_religion.setText("");
    ins_ocupacion.setText("");
    ins_telcasa.setText("");
    ins_correo.setText("");
    ins_calle.setText("");
    ins_numext.setText("");
    ins_colonia.setSelectedIndex(0);
    ins_municipio.setSelectedIndex(0);
    ins_cp.setSelectedIndex(0);
}
    
    public void validacion(){
    
    if(ins_nombre.getText().isEmpty() || ins_edad.getText().isEmpty() ||ins_sexo.getSelectedItem().equals("SELECCIONE") || 
    ins_año.getSelectedItem().equals("AÑO") || ins_estadocivil.getSelectedItem().equals("SELECCIONE") || 
    ins_telefonomovil.getText().isEmpty() ||  ins_escolaridad1.getSelectedItem().equals("SELECCIONE") || ins_horastra.getSelectedItem().equals("SELECCIONE") || 
    ins_curp.getText().isEmpty() || ins_religion.getText().isEmpty() || ins_ocupacion.getText().isEmpty() || ins_telcasa.getText().isEmpty() || ins_correo.getText().isEmpty()
            || ins_calle.getText().isEmpty() || ins_numext.getText().isEmpty()){
    
        bot_agregar.setEnabled(false);
        
    }else{
    
         bot_agregar.setEnabled(true);
    }


}
    private static Connection conexioncom;
    private static PreparedStatement sentenica_preparadacom;
    private static ResultSet resultadocom;
    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JLabel();
        txt_edad = new javax.swing.JLabel();
        txt_sexo = new javax.swing.JLabel();
        txt_nacimiento = new javax.swing.JLabel();
        txt_hijos = new javax.swing.JLabel();
        txt_civil = new javax.swing.JLabel();
        txt_hrstrabajo = new javax.swing.JLabel();
        txt_escolaridad = new javax.swing.JLabel();
        txt_profesion = new javax.swing.JLabel();
        txt_ocupacion = new javax.swing.JLabel();
        txt_nocasa = new javax.swing.JLabel();
        txt_religion = new javax.swing.JLabel();
        txt_telefonomovil = new javax.swing.JLabel();
        txt_correo = new javax.swing.JLabel();
        ins_nombre = new javax.swing.JTextField();
        ins_sexo = new javax.swing.JComboBox<>();
        ins_estadocivil = new javax.swing.JComboBox<>();
        ins_año = new javax.swing.JComboBox<>();
        ins_religion = new javax.swing.JTextField();
        ins_telefonomovil = new javax.swing.JTextField();
        ins_escolaridad1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ins_curp = new javax.swing.JTextField();
        ins_ocupacion = new javax.swing.JTextField();
        ins_telcasa = new javax.swing.JTextField();
        ins_correo = new javax.swing.JTextField();
        ins_numhijos = new javax.swing.JComboBox<>();
        ins_edad = new javax.swing.JTextField();
        txt_apellidop = new javax.swing.JLabel();
        txt_apellidop1 = new javax.swing.JLabel();
        ins_apellidom = new javax.swing.JTextField();
        ins_apellidop = new javax.swing.JTextField();
        ins_horastra = new javax.swing.JComboBox<>();
        txt_escolaridad1 = new javax.swing.JLabel();
        ins_calle = new javax.swing.JTextField();
        txt_escolaridad2 = new javax.swing.JLabel();
        txt_escolaridad3 = new javax.swing.JLabel();
        ins_municipio = new javax.swing.JComboBox<>();
        ins_numext = new javax.swing.JTextField();
        ins_colonia = new javax.swing.JComboBox<>();
        txt_escolaridad5 = new javax.swing.JLabel();
        ins_cp = new javax.swing.JComboBox<>();
        txt_ocupacion2 = new javax.swing.JLabel();
        OPCIONES = new javax.swing.JPanel();
        bot_agregar = new javax.swing.JButton();
        bot_agregar1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("ALTA DE NUEVO PACIENTE");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "INGRESE LOS DATOS DEL PACIENTE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        txt_nombre.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_nombre.setText("NOMBRE (S)");

        txt_edad.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_edad.setText("EDAD");

        txt_sexo.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_sexo.setText("SEXO");

        txt_nacimiento.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_nacimiento.setText("AÑO DE NACIMIENTO");

        txt_hijos.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_hijos.setText("NUMERO DE HIJOS");

        txt_civil.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_civil.setText("ESTADO CIVIL");

        txt_hrstrabajo.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_hrstrabajo.setText("HRS. DE TRABAJO");

        txt_escolaridad.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_escolaridad.setText("ESCOLARIDAD");

        txt_profesion.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_profesion.setText("CURP");

        txt_ocupacion.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_ocupacion.setText("OCUPACION");

        txt_nocasa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_nocasa.setText("TELEFONO DE CASA");

        txt_religion.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_religion.setText("RELIGION");

        txt_telefonomovil.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_telefonomovil.setText("TELEFONO MOVIL");

        txt_correo.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_correo.setText("CORREO ELECTRONICO");

        ins_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_nombreActionPerformed(evt);
            }
        });
        ins_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_nombreKeyTyped(evt);
            }
        });

        ins_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "FEMENINO", "MASCULINO", "OTRO" }));
        ins_sexo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_sexoItemStateChanged(evt);
            }
        });

        ins_estadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "SOLTERO (A)", "CASADO (A)", "OTRO" }));
        ins_estadocivil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_estadocivilItemStateChanged(evt);
            }
        });

        ins_año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AÑO" }));
        ins_año.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_añoItemStateChanged(evt);
            }
        });
        ins_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_añoActionPerformed(evt);
            }
        });

        ins_religion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_religionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_religionKeyTyped(evt);
            }
        });

        ins_telefonomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_telefonomovilActionPerformed(evt);
            }
        });
        ins_telefonomovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_telefonomovilKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_telefonomovilKeyTyped(evt);
            }
        });

        ins_escolaridad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "NINGUNA", "PRIMARIA", "SECUNDARIA", "PREPARATORIA", "BACHILLERARO", "TECNICO", "TECNICO SUPERIOR", "LICENCIATURA", "POSGRADO" }));
        ins_escolaridad1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_escolaridad1ItemStateChanged(evt);
            }
        });

        ins_curp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_curpActionPerformed(evt);
            }
        });
        ins_curp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_curpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_curpKeyTyped(evt);
            }
        });

        ins_ocupacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_ocupacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_ocupacionKeyTyped(evt);
            }
        });

        ins_telcasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_telcasaActionPerformed(evt);
            }
        });
        ins_telcasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_telcasaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_telcasaKeyTyped(evt);
            }
        });

        ins_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_correoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_correoKeyTyped(evt);
            }
        });

        ins_numhijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        ins_numhijos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_numhijosItemStateChanged(evt);
            }
        });

        ins_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_edadActionPerformed(evt);
            }
        });
        ins_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_edadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_edadKeyTyped(evt);
            }
        });

        txt_apellidop.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_apellidop.setText("APELLIDO PATERNO");

        txt_apellidop1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_apellidop1.setText("APELLIDO MATERNO");

        ins_apellidom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_apellidomActionPerformed(evt);
            }
        });
        ins_apellidom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_apellidomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_apellidomKeyTyped(evt);
            }
        });

        ins_apellidop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_apellidopActionPerformed(evt);
            }
        });
        ins_apellidop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_apellidopKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_apellidopKeyTyped(evt);
            }
        });

        ins_horastra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "NINGUNA", "1 HORA", "2 HORAS", "3 HORAS", "4 HORAS", "5 HORAS", "6 HORAS", "7 HORAS", "8 HORAS", "9 HORAS", "10 HORAS", "11 HORAS", "12 HORAS", "13 HORAS", "14 HORAS", "15 HORAS", "16 HORAS", "+ DE 16 HORAS" }));
        ins_horastra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_horastraItemStateChanged(evt);
            }
        });

        txt_escolaridad1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_escolaridad1.setText("CALLE ");

        ins_calle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_calleKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_calleKeyTyped(evt);
            }
        });

        txt_escolaridad2.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_escolaridad2.setText("NUMERO EXT.");

        txt_escolaridad3.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_escolaridad3.setText("MUNICIPIO");

        ins_municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        ins_municipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_municipioItemStateChanged(evt);
            }
        });
        ins_municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_municipioActionPerformed(evt);
            }
        });
        ins_municipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_municipioKeyReleased(evt);
            }
        });

        ins_numext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_numextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ins_numextKeyTyped(evt);
            }
        });

        ins_colonia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_coloniaItemStateChanged(evt);
            }
        });
        ins_colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_coloniaActionPerformed(evt);
            }
        });

        txt_escolaridad5.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_escolaridad5.setText("CP");

        ins_cp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "56617", "57800", "57820" }));
        ins_cp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ins_cpItemStateChanged(evt);
            }
        });
        ins_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_cpActionPerformed(evt);
            }
        });
        ins_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ins_cpKeyReleased(evt);
            }
        });

        txt_ocupacion2.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_ocupacion2.setText("COLONIA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ins_numhijos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_profesion)
                    .addComponent(txt_nombre)
                    .addComponent(ins_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellidop)
                    .addComponent(ins_apellidop, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellidop1)
                    .addComponent(ins_apellidom, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_edad)
                    .addComponent(ins_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sexo)
                    .addComponent(ins_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nacimiento)
                    .addComponent(ins_año, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hijos))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ins_escolaridad1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_correo)
                            .addComponent(ins_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ins_telefonomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telefonomovil)
                            .addComponent(ins_telcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nocasa)
                            .addComponent(ins_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_religion)
                            .addComponent(ins_estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_civil)
                            .addComponent(ins_horastra, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hrstrabajo)
                            .addComponent(txt_escolaridad)
                            .addComponent(ins_religion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ocupacion))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ins_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ocupacion2)
                            .addComponent(ins_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_escolaridad5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ins_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_escolaridad3)
                            .addComponent(ins_numext, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_escolaridad2)
                            .addComponent(ins_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_escolaridad1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel2)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_profesion)
                    .addComponent(txt_escolaridad)
                    .addComponent(txt_escolaridad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_escolaridad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txt_nombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hrstrabajo)
                            .addComponent(txt_escolaridad2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_horastra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_numext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_civil)
                            .addComponent(txt_apellidop)
                            .addComponent(txt_escolaridad3))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ins_estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ins_apellidop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ins_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_religion)
                            .addComponent(txt_apellidop1)
                            .addComponent(txt_escolaridad5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ins_religion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ins_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ins_apellidom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ocupacion)
                    .addComponent(txt_edad)
                    .addComponent(txt_ocupacion2))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sexo)
                    .addComponent(txt_nocasa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ins_telcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nacimiento)
                    .addComponent(txt_telefonomovil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_telefonomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hijos)
                    .addComponent(txt_correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_numhijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        OPCIONES.setBackground(new java.awt.Color(255, 255, 255));
        OPCIONES.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPCIONES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        bot_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        bot_agregar.setText("GUARDAR");
        bot_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bot_agregar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bot_agregar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bot_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_agregarActionPerformed(evt);
            }
        });

        bot_agregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar (2).png"))); // NOI18N
        bot_agregar1.setText("BORRAR");
        bot_agregar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bot_agregar1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bot_agregar1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bot_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_agregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OPCIONESLayout = new javax.swing.GroupLayout(OPCIONES);
        OPCIONES.setLayout(OPCIONESLayout);
        OPCIONESLayout.setHorizontalGroup(
            OPCIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OPCIONESLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(OPCIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bot_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(bot_agregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        OPCIONESLayout.setVerticalGroup(
            OPCIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OPCIONESLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(bot_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(bot_agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OPCIONES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OPCIONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(236, 236, 236))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ins_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_añoActionPerformed
         
         // TODO add your handling code here:
    }//GEN-LAST:event_ins_añoActionPerformed

    private void bot_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_agregarActionPerformed
   
 
    curp1 = ins_curp.getText(); 
    nombre1 = ins_nombre.getText();
    apellidop1 = ins_apellidop.getText();
    apellidom1 = ins_apellidom.getText();
    edad1 = Integer.parseInt((String) ins_edad.getText());
    sexo1 = ins_sexo.getSelectedItem().toString(); 
    año1 = Integer.parseInt((String) ins_año.getSelectedItem());
    nohijos1 = Integer.parseInt((String) ins_numhijos.getSelectedItem()); 
    estcivil1 = ins_estadocivil.getSelectedItem().toString(); 
    escolaridad1 = ins_escolaridad1.getSelectedItem().toString();
    hrtrabajo1 = ins_horastra.getSelectedItem().toString();
    Ocupacion1 = ins_ocupacion.getText(); 
    Religion1 = ins_religion.getText(); 
    tel_cas1 = Integer.parseInt((String) ins_telcasa.getText()); 
    tel_mov1 = ins_telefonomovil.getText(); 
    correo1 = ins_correo.getText();
        
        
    metodos.guardar_datos_paciente(curp1, nombre1, apellidop1, apellidom1, edad1, sexo1, año1, nohijos1, estcivil1, escolaridad1, 
            hrtrabajo1, Ocupacion1, Religion1, tel_cas1, tel_mov1, correo1);
    
    
    calle1 = ins_calle.getText(); 
    numext1 = ins_numext.getText(); 
    clvmun = ins_municipio.getSelectedItem().toString();
    cpnum = ins_cp.getSelectedItem().toString();
    clvcol = ins_colonia.getSelectedItem().toString();
    idpa = ins_curp.getText(); 
    
    
    metodos2.guardar_direccionPc(calle1,numext1,clvmun,cpnum,clvcol,idpa);
    
    
    clean();
        // TODO add your handling code here:
    }//GEN-LAST:event_bot_agregarActionPerformed

    private void ins_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_nombreActionPerformed
          
// TODO add your handling code here:
    }//GEN-LAST:event_ins_nombreActionPerformed

    private void ins_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_nombreKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        } 
         if (ins_nombre.getText().length() >= 40) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        } 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_nombreKeyTyped

    private void ins_telefonomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_telefonomovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_telefonomovilActionPerformed

    private void ins_telefonomovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_telefonomovilKeyTyped
         Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        } 
         if (ins_telefonomovil.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        } 

        // TODO add your handling code here:
    }//GEN-LAST:event_ins_telefonomovilKeyTyped

    private void ins_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_edadKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        } 
         if (ins_edad.getText().length() >= 2) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_edadKeyTyped

    private void ins_religionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_religionKeyTyped
          Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        } 
         if (ins_religion.getText().length() >= 40) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        } 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_religionKeyTyped

    private void ins_ocupacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_ocupacionKeyTyped
          Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        } 
         if (ins_ocupacion.getText().length() >= 40) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_ocupacionKeyTyped

    private void ins_telcasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_telcasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_telcasaActionPerformed

    private void ins_telcasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_telcasaKeyTyped
           Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        } 
         if (ins_telcasa.getText().length() >= 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_telcasaKeyTyped

    private void ins_correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_correoKeyTyped
        
         if (ins_curp.getText().length() >= 60) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_correoKeyTyped

    private void bot_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_agregar1ActionPerformed
         clean();
        // TODO add your handling code here:
    }//GEN-LAST:event_bot_agregar1ActionPerformed

    private void ins_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_nombreKeyReleased
    validacion();
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_nombreKeyReleased

    private void ins_edadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_edadKeyReleased
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_edadKeyReleased

    private void ins_telefonomovilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_telefonomovilKeyReleased
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_telefonomovilKeyReleased

    private void ins_religionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_religionKeyReleased
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_religionKeyReleased

    private void ins_ocupacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_ocupacionKeyReleased
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_ocupacionKeyReleased

    private void ins_telcasaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_telcasaKeyReleased
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_telcasaKeyReleased

    private void ins_correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_correoKeyReleased
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_correoKeyReleased

    private void ins_sexoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_sexoItemStateChanged
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_sexoItemStateChanged

    private void ins_añoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_añoItemStateChanged
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_añoItemStateChanged

    private void ins_numhijosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_numhijosItemStateChanged
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_numhijosItemStateChanged

    private void ins_estadocivilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_estadocivilItemStateChanged
validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_estadocivilItemStateChanged

    private void ins_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_edadActionPerformed

    private void ins_apellidomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_apellidomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_apellidomActionPerformed

    private void ins_apellidomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_apellidomKeyReleased
validacion();         // TODO add your handling code here:
    }//GEN-LAST:event_ins_apellidomKeyReleased

    private void ins_apellidomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_apellidomKeyTyped
 Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (ins_apellidop.getText().length() >= 20) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }             // TODO add your handling code here:
    }//GEN-LAST:event_ins_apellidomKeyTyped

    private void ins_apellidopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_apellidopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_apellidopActionPerformed

    private void ins_apellidopKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_apellidopKeyReleased
validacion();         // TODO add your handling code here:
    }//GEN-LAST:event_ins_apellidopKeyReleased

    private void ins_apellidopKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_apellidopKeyTyped
 Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (ins_apellidop.getText().length() >= 20) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ins_apellidopKeyTyped

    private void ins_escolaridad1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_escolaridad1ItemStateChanged
        validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_escolaridad1ItemStateChanged

    private void ins_curpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_curpKeyTyped
        Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (ins_curp.getText().length() >= 18) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_curpKeyTyped

    private void ins_curpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_curpKeyReleased
        validacion();        // TODO add your handling code here:
    }//GEN-LAST:event_ins_curpKeyReleased

    private void ins_curpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_curpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_curpActionPerformed

    private void ins_horastraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_horastraItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_horastraItemStateChanged

    private void ins_calleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_calleKeyReleased
validacion();         // TODO add your handling code here:
    }//GEN-LAST:event_ins_calleKeyReleased

    private void ins_calleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_calleKeyTyped
Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (ins_calle.getText().length() >= 15) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ins_calleKeyTyped

    private void ins_municipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_municipioItemStateChanged
MunicipioVO d = (MunicipioVO)this.ins_municipio.getSelectedItem();
     int id = d.getCLAVE_MUNICIPIO();
     COP.listar_codigopostal(ins_cp, id);        // TODO add your handling code here:
    }//GEN-LAST:event_ins_municipioItemStateChanged

    private void ins_numextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_numextKeyReleased
validacion();         // TODO add your handling code here:
    }//GEN-LAST:event_ins_numextKeyReleased

    private void ins_numextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_numextKeyTyped
Character c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
        if (ins_numext.getText().length() >= 15) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ins_numextKeyTyped

    private void ins_coloniaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_coloniaItemStateChanged
         // TODO add your handling code here:
    }//GEN-LAST:event_ins_coloniaItemStateChanged

    private void ins_municipioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_municipioKeyReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_ins_municipioKeyReleased

    private void ins_cpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ins_cpItemStateChanged
 CodigopostalVO d = (CodigopostalVO)this.ins_cp.getSelectedItem();
     int id = d.getCP();
     COL.listar_colonia(ins_colonia, id);          // TODO add your handling code here:
    }//GEN-LAST:event_ins_cpItemStateChanged

    private void ins_cpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ins_cpKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_cpKeyReleased

    private void ins_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_cpActionPerformed

    private void ins_coloniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_coloniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_coloniaActionPerformed

    private void ins_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_municipioActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_municipioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OPCIONES;
    private javax.swing.JButton bot_agregar;
    private javax.swing.JButton bot_agregar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ins_apellidom;
    private javax.swing.JTextField ins_apellidop;
    private javax.swing.JComboBox<String> ins_año;
    private javax.swing.JTextField ins_calle;
    private javax.swing.JComboBox<String> ins_colonia;
    private javax.swing.JTextField ins_correo;
    public static javax.swing.JComboBox<String> ins_cp;
    private javax.swing.JTextField ins_curp;
    private javax.swing.JTextField ins_edad;
    private javax.swing.JComboBox<String> ins_escolaridad1;
    private javax.swing.JComboBox<String> ins_estadocivil;
    private javax.swing.JComboBox<String> ins_horastra;
    public static javax.swing.JComboBox<String> ins_municipio;
    private javax.swing.JTextField ins_nombre;
    private javax.swing.JTextField ins_numext;
    private javax.swing.JComboBox<String> ins_numhijos;
    private javax.swing.JTextField ins_ocupacion;
    private javax.swing.JTextField ins_religion;
    private javax.swing.JComboBox<String> ins_sexo;
    private javax.swing.JTextField ins_telcasa;
    private javax.swing.JTextField ins_telefonomovil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_apellidop;
    private javax.swing.JLabel txt_apellidop1;
    private javax.swing.JLabel txt_civil;
    private javax.swing.JLabel txt_correo;
    private javax.swing.JLabel txt_edad;
    private javax.swing.JLabel txt_escolaridad;
    private javax.swing.JLabel txt_escolaridad1;
    private javax.swing.JLabel txt_escolaridad2;
    private javax.swing.JLabel txt_escolaridad3;
    private javax.swing.JLabel txt_escolaridad5;
    private javax.swing.JLabel txt_hijos;
    private javax.swing.JLabel txt_hrstrabajo;
    private javax.swing.JLabel txt_nacimiento;
    private javax.swing.JLabel txt_nocasa;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_ocupacion;
    private javax.swing.JLabel txt_ocupacion2;
    private javax.swing.JLabel txt_profesion;
    private javax.swing.JLabel txt_religion;
    private javax.swing.JLabel txt_sexo;
    private javax.swing.JLabel txt_telefonomovil;
    // End of variables declaration//GEN-END:variables
}
